# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('get_a_room_app', '0002_auto_20170409_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
